version: "3"

services:
  app:
    build: .
    platform: linux
    volumes:
      - ./:/usr/app
    command: "npm run start:dev"
    ports:
      - 8000:3000
    networks:
      - app_network
networks:
  app_network:
